version: '3.8'
services:
  db:
    image: postgres:14.21
    container_name: pg_astreya
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal
  vault:
    image: vault:1.12.0
    container_name: vault
    env_file:
      - .env
    volumes:
      - vault_data:/vault/file
    ports:
      - "8200:8200"
    command: server
    networks:
      - internal
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zk_astreya
    ports:
      - "2181:2181"
    networks:
      - internal
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka_astreya
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    networks:
      - internal
  bitrix:
    image: bitrixvm:24.0-php8.2
    container_name: bitrix_astreya
    env_file:
      - .env
    volumes:
      - ./bitrix:/var/www/bitrix
    ports:
      - "8080:80"
    networks:
      - internal
  nocodb:
    image: nocodb/nocodb:0.258.0
    container_name: nocodb_astreya
    env_file:
      - .env
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
  n8n:
    image: n8nio/n8n:1.95.0
    container_name: n8n_astreya
    env_file:
      - .env
    ports:
      - "5678:5678"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
  unzipper:
    image: alpine:3.18
    container_name: unzipper
    entrypoint: ["sleep", "infinity"]
    volumes:
      - ./archives:/archives
      - ./extracted:/extracted
networks:
  internal:
volumes:
  pg_data:
  vault_data:
